### ISSUE TITLE
小小提示

### ISSUE THREAD

**Issue by zhoujianhanyu** [Werb/GankWithZhihu#1]
//允许为空，不是所有都要实现MVP模式
        if(createPresenter()!=null) {
            mPresenter = createPresenter();
            mPresenter.attachView((V) this);
        }

**Comment by werbhelius** [comment]
哪里出了问题？：)

**Comment by zhoujianhanyu** [comment]
如果createPresenter()不为null，就创建了两个对象。

**Comment by forezp** [comment]
创建了2次，大神
  zhihuApi.getBeforetNews(time)
                    .subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(newsTimeLine -> {
                        disPlayZhihuList(newsTimeLine,context,zhihuFgView,mRecyclerView);
                    },this::loadError);

这段代码不是很懂，请大神详解下。

**Comment by zhoujianhanyu** [comment]
@forezp 这个是rx语法来着，学习一下rxjava，rxAndroid应该就可以看懂了。

**Comment by werbhelius** [comment]
我晚上回去打debug看一下，最近疯狂加班...有些忙...

**Comment by werbhelius** [comment]
我打debug看了一下，这里只是判断createPresenter()!=null，不存在引用对象的，只有一个mPresenter在引用。

**Comment by zhoujianhanyu** [comment]
@Werb 我的意思是没必要去new 两个对象啊。
mPresenter = createPresenter();
if(mPresenter!=null) {
mPresenter.attachView((V) this);
}
这样不是更好么？

**Comment by werbhelius** [comment]
有道理，谢谢提醒。:-)
