### ISSUE TITLE
some problem about ApiRetrofit.class

### ISSUE THREAD

**Issue by hkq325800** [Werb/GankWithZhihu#3]
根据你在ApiRetrofit中构造函数里的代码 猜想你是希望建立一个ApiRetrofit实例 然后分别获取ZhihuApi、GankApi和DailyApi的单例对象 但是现在ApiFactory的代码显然会创建三个ApiRetrofit实例然后分别获取单例对象 改进方法也简单 在ApiRetrofit里放一个static ApiRetrofit instance;然后getInstance单例获取就好了

According to your code in method 'ApiRetrofit()' ,I guess you want to get an instance for class ApiRetrofit,and then get three Api instances in ApiFactory.One way to fix this:Add 'static ApiRetrofit instance;'in ApiRetrofit.class and then use getInstance() to get it.

**Comment by ichapter** [comment]
在知乎页下拉的时候，突然崩溃，日志如下：
09-18 14:27:59.344 3691-3691/com.werb.gankwithzhihu E/ActivityThread: Activity com.werb.gankwithzhihu.ui.activity.GankWebActivity has leaked IntentReceiver android.widget.ZoomButtonsController$1@3b74978 that was originally registered here. Are you missing a call to unregisterReceiver()?

**Comment by forezp** [comment]
我知道为什么，这 是adapter 为空，可以判断下，在监听下拉的时候
