### ISSUE TITLE
retrofit2 有@url注解，可以动态组装url, 应该不用搞多个retrofit实例吧

### ISSUE THREAD

**Issue by imishx** [Werb/GankWithZhihu#4]
？

**Comment by werbhelius** [comment]
确实retrofit现在存在多个实例，这是需要优化的地方，当时也没想那么多。
但有几点：
1. 现在是对三类api访问，正常项目中，我们肯定只有一个后台服务器，那么对应的也应该只有一个retrofit实例。
2.既然我们现在是对三个api访问，理论上是可以简单的通过url来配置，但如果我们想对三种api设置不同的拦截器，比如有些要缓存有些不要缓存，有些需要保存cookie信息，有些需要GSON解析有些不需要，那么只有一个retrofit实例的话，在操作上一定是会不方便的。
（虽然上述情况，目前项目中还没有涉及到...）
我会接下来好好优化一下，最后谢谢提建议啦
