### ISSUE TITLE
那啥.................

### ISSUE THREAD

**Issue by cjcj125125** [Werb/GankWithZhihu#5]
那啥，闪退频率有点高，最近也在搞mvp+rxjava+retrofit，可以互相切磋下，还望给个机会

**Comment by werbhelius** [comment]
加我微信吧 1025004680

**Comment by shenqiwen** [comment]
看到标题,我没忍住....

**Comment by vejei** [comment]
问一下，你们学习mvp都从哪学的，官方貌似没有文档的

**Comment by shenqiwen** [comment]
@zeleven  官方有Demo啊 https://github.com/googlesamples/android-architecture
